### ISSUE TITLE
Is TFD-Example map file not completed?

### ISSUE THREAD

**Issue by Chaowei0820** [AIR-THU/DAIR-V2X-Seq#13]
Hi all, I follow  "docs/benchmarks/vic-traj-forecasting/TNT/README.md" , but I got some mistake at this step: 
python core/util/preprocessor/tfd_preprocess.py --root ${DATA_ROOT}/single-vehicle/trajectorie

  File "core/util/preprocessor/tfd_preprocess.py", line 66, in __getitem__
    return self.process_and_save(df, seq_id=seq_f_name, dir_=self.save_dir)
  File "./core/util/preprocessor/base.py", line 114, in process_and_save
    df_processed = self.process(dataframe, seq_id, map_feat)
  File "core/util/preprocessor/tfd_preprocess.py", line 70, in process
    data = self.get_obj_feats(data)
  File "core/util/preprocessor/tfd_preprocess.py", line 164, in get_obj_feats
    ctr_line_candts = self.dm.get_candidate_centerlines_for_traj(agt_traj_obs, data['city'], viz=False)
  File "/media/didi/Data/py_project/argoverse-api/argoverse/map_representation/map_api.py", line 878, in get_candidate_centerlines_for_traj
    candidates_future = self.dfs(lane, city_name, 0, dfs_threshold)
  File "/media/didi/Data/py_project/argoverse-api/argoverse/map_representation/map_api.py", line 965, in dfs
    centerline = self.get_lane_segment_centerline(child, city_name)
  File "/media/didi/Data/py_project/argoverse-api/argoverse/map_representation/map_api.py", line 721, in get_lane_segment_centerline
    lane_centerline = self.city_lane_centerlines_dict[city_name][lane_segment_id].centerline
KeyError: '23182002_1_-3'

The dataset i used is TFD-Example, is  the map files not completed?

**Comment by guspan-tanadi** [comment]
the folder /single-vehicle/trajectorie or /single-vehicle/trajectorie**s**
end of command showing /single-vehicle/trajectorie

**Comment by Chaowei0820** [comment]
> the folder /single-vehicle/trajectorie or /single-vehicle/trajectorie**s** end of command showing /single-vehicle/trajectorie

Thank you for reply. 
I missed a "s" when i wrote this comment , and the folder i actually used  is /single-vehicle/trajectories.
Then I got this mistake.

I print some debug info at this "build_centerline_index" function at dair_map_api.py. 
I found the "yizhuang_PEK_vector_map.json"  file contains 
lane_id with '23181777_1_-3'   and its successors ['**23182002_1_-3**']  predecessors ['23181778_1_-3'],
**but not** contains land_id with '**23182002_1_-3**'

The map data will cause a key error at the function "get_lane_segment_successor_ids" in "argoverse-api/argoverse/map_representation/map_api.py" .
successor_ids = self.city_lane_centerlines_dict[city_name][lane_segment_id].successors

So i think the "yizhuang_PEK_vector_map.json" caused the error.
Do you have a solution?  Thank you for your attention!

**Comment by Chaowei0820** [comment]
> > the folder /single-vehicle/trajectorie or /single-vehicle/trajectorie**s** end of command showing /single-vehicle/trajectorie
> 
> Hi @guspan-tanadi Thank you for your reply. I missed a "s" when i wrote this comment , and the folder i actually used is /single-vehicle/trajectories. Then I got this mistake.
> 
> I print some debug info at this "build_centerline_index" function at dair_map_api.py. I found the "yizhuang_PEK_vector_map.json" file contains lane_id with '23181777_1_-3' and its successors ['**23182002_1_-3**'] predecessors ['23181778_1_-3'], **but not** contains lane_id with '**23182002_1_-3**'
> 
> The map data will cause a key error at the function "get_lane_segment_successor_ids" in "argoverse-api/argoverse/map_representation/map_api.py" . successor_ids = self.city_lane_centerlines_dict[city_name][lane_segment_id].successors
> 
> So i think the "yizhuang_PEK_vector_map.json" caused the error. Do you have a solution? Thank you for your attention!

I fix the problem by using the full map files at the full TFD dataset to replace example dataset. Thank you.

**Comment by haibao-yu** [comment]
Thanks for your feedback. We have add the full maps and update the **[TFD-Example](https://drive.google.com/file/d/1-Ri92z6rkH14vAOFOx5xhfzvFxBptgAA/view?usp=drive_link).** , please try it again.
