### ISSUE TITLE
Data question

### ISSUE THREAD

**Issue by Wansit99** [AIR-THU/DAIR-V2X-Seq#18]
Hello,I encountered some confusion while using the dataset.Why is there a step for data fusion preprocessing? I noticed that the dataset already contains vehicle-to-infrastructure cooperative data. Why is there still a need to fuse them separately from different perspectives?

**Comment by HzRynn** [comment]
The trajectories in the cooperative vehicle-infrastructure directory are for reference. Before prediction, we should fuse the trajectories from the vehicle-trajectories set and the infrastructure-trajectories set.
