### ISSUE TITLE
Error about "dair_v2x_tfd_tutorial"

### ISSUE THREAD

**Issue by YilinGao-SHU** [AIR-THU/DAIR-V2X-Seq#19]
Thanks for your work, but when I try to visualize  the dataset by running dair_v2x_tfd_tutorial.py(rewrited the dair_v2x_tfd_tutorial.ipynb) I get the following error,
`Traceback (most recent call last):
  File "dair_v2x_tfd_tutorial.py", line 5, in <module>
    from dair_map_api import DAIRV2XMap
  File "/DAIR-V2X-Seq-main/projects/dataset/dair_map_api.py", line 32, in <module>
    ROOT = os.path.join(os.environ.get('DATA_ROOT'), 'map_files')
  File "/opt/anaconda3/envs/-/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType`
and I found that there is no such a class called 'DAIRMap' in tfd_visualize.py, is there something wrong here?

**Comment by fengzhongdecaiyun** [comment]
The same question
