### ISSUE TITLE
The trained online.ckpt and offline.ckpt provided by the author are missing

### ISSUE THREAD

**Issue by KYM1125** [AIR-THU/DAIR-V2X-Seq#22]
The main branch of DAIR-V2X-Seq does not contain the path 
![QQ20240101-145431](https://github.com/AIR-THU/DAIR-V2X-Seq/assets/95025981/358960e0-65b9-42af-88b8-77e9b03fd6a3)
projects/HiVT_plugin/checkpoints.

**Comment by haibao-yu** [comment]
We have uploaded the checkpoint, please check again.
