### ISSUE TITLE
Conversion from the coordinates of SPD to the coordinates of HDmap in TFD

### ISSUE THREAD

**Issue by Uchan1996** [AIR-THU/DAIR-V2X-Seq#32]
I want to visualize the detected objects on HDmaps.
Is there any conversion matrix from the coordinate of SPD to the coordinate of HDmaps in TFD?
In my understanding, the world coordinate of SPD is different from the world coordinate of TFD.
I tried to convert the lidar coordinates of SPD by using 'calib/virtuallidar_to_world', but the converted coordinates are totally different from the coordinates of HDmaps.

**Comment by ry4nzhu** [comment]
Hi, I am working on something similar. Have you solved this problem? 

Thanks.

**Comment by Uchan1996** [comment]
SPD datasets also include json maps, so you can calculate the offsets to convert the SPD coordinates to TFD coordinates by comparing between SPD maps and TFD maps.
In my calculation, the offsets are as follows:

"offset_x": 415837.234278,
"offset_y": 4730400.970671999

You can convert SPD coordinates to TFD coordinates just by adding the above offsets to your detected results.

**Comment by ry4nzhu** [comment]
Thanks for the reply!

**Comment by MMMaverick** [comment]
Hello, I would like to display the ego-car position from the SPD dataset (obtained by transforming the point cloud into the world coordinate system) on the vector map from the SPD dataset. Although the final visualization shows that they are in the same numerical range and coordinate system, there is still a significant discrepancy. Do you have any ideas on this? Additionally, apart from the different coordinate systems, what are the differences between the map data of SPD and TFD? Thank you for your response.

**Comment by Uchan1996** [comment]
@MMMaverick 
Sorry, my explanation was insufficient.
Detected SPD results are on the lidar coordinate if you use a LiDAR-based detector.
You have to convert the coordinate of the detected results to the world coordinate before adding the above offsets because the map coordinates are the world coordinate.
Please refer to the coordinate definitions of DAIR-V2X datasets at the link below:
https://github.com/AIR-THU/DAIR-V2X/blob/main/v2x/v2x_utils/transformation_utils.py#L68C1-L68C36

I also don't know what the difference between SPD maps and TFD maps is and why there are two types of maps.

**Comment by MMMaverick** [comment]
Thank you for your response! I think I have a rough idea of where the issue lies. It seems that I split the entire data into multiple segments and used the position of the ego-car in the first frame of each segment as the origin to correct the world coordinate system. I am currently checking my code. The map I obtained from the SPD data download link and the TFD data download link are of the same area, but their coordinate systems are not quite consistent, and I'm not sure of the reason yet. @Uchan1996
