### ISSUE TITLE
wish for the source code

### ISSUE THREAD

**Issue by LuckyDush** [AIR-THU/DAIR-V2X-Seq#4]
Excellent work! Hope that you can release the Training&Evaluation code for VID Forecasting,especially how you train your benchmark TNT and HiVT online and offline.

**Comment by haibao-yu** [comment]
We have released our source code: https://github.com/AIR-THU/DAIR-V2X for SPD, https://github.com/AIR-THU/DAIR-V2X-Seq for TFD.
