### ISSUE TITLE
dataset download problem

### ISSUE THREAD

**Issue by Yolan1013** [AIR-THU/DAIR-V2X-Seq#7]
Thank you for your excellent work! 
But i met the problem when i try to download dataset form the official website. I have waited for several days, but the result is still the same. Can you help me with that?
![Screenshot from 2023-09-01 14-17-36](https://github.com/AIR-THU/DAIR-V2X-Seq/assets/34823398/7112f8cd-7a64-48c7-bf8f-b29a13f50daf)

**Comment by haibao-yu** [comment]
The problem has been solved.
