### ISSUE TITLE
Dataset request -- V2X-Seq -- Outside Mainland China #74

### ISSUE THREAD

**Issue by DerejeCShenkut** [AIR-THU/DAIR-V2X-Seq#8]
Hi,

I have repeatedly emailed [dair@air.tsinghua.edu.cn](mailto:dair@air.tsinghua.edu.cn) requesting a download link for research outside China.
Can you please respond?

Thanks,

**Comment by haibao-yu** [comment]
Please refer to https://github.com/AIR-THU/DAIR-V2X/issues/78.
